### ISSUE TITLE
Clarification needed: Mapping between method "Robust FlowNetC" and code in repository

### ISSUE THREAD

**Issue by voei** [lmb-freiburg/understanding_flow_robustness#1]
Hi, the linked paper mentions a specific implementation of the method "Robust FlowNetC", but it is not clear to me which file and configuration in the Github repository corresponds to it.
As per my understanding, the method "Robust FlowNetC" corresponds to the configuration of "FlowNetC_flexible_larger_field" with both kernel size and number of reps set to 3. However, this is not explicitly mentioned in the code or in the paper, or at least I have not found it anywhere.
Could you clarify that for me? Thanks!

**Comment by SimonSchrodi** [comment]
Hi, 
yes, you're absolutely right. The implementation is in [FlowNetC_flexible_larger_field.py](https://github.com/lmb-freiburg/understanding_flow_robustness/blob/main/models/FlowNetC_flexible_larger_field.py). By setting `kernel_size=3` and `number_of_reps=3` you can get the Robust FlowNetC. You can also easily fetch it with "FlowNetCFlexLarger_k3_reps3" via [fetch_model](https://github.com/lmb-freiburg/understanding_flow_robustness/blob/main/models/utils_model.py#L27).
